Adding support for DPoP.
eu-digital-identity-wallet/eudi-srv-pid-issuer pull request #139
Opened 2024-04-19 14:23 UTC by dzarras

2024-04-19 14:25 UTC, dzarras commented
Currently mDL issuance is working as expected using DPoP.

PID issuance is currently not working because we can no longer use the userinfo endpoint to fetch the user's details.
Currently investigating keycloak-admin client to see if it's a viable alternative.

2024-04-19 21:36 UTC, dzarras commented
GetPidFromAuthServer has been implemented using Keycloak admin client. PID issuance has been reinstated.
Leaving this as a draft to better check on Monday whether we are missing anything else.

2024-04-22 08:14 UTC, babisRoutis commented
@dzarras Please rebase with main

2024-04-22 10:54 UTC, babisRoutis requested changes

2024-04-22 10:54 UTC, babisRoutis commented on src/main/kotlin/eu/europa/ec/eudi/pidissuer/port/input/AuthorizationContext.kt
> +typealias AccessToken = String
Consider using the base class `AccessToken` from Nimbus

2024-04-22 10:54 UTC, babisRoutis commented on src/main/kotlin/eu/europa/ec/eudi/pidissuer/security/DPoPConfigurationProperties.kt
> +@ConfigurationProperties("spring.security.oauth2.resourceserver.dpop")
Why use annotations?

2024-04-22 10:54 UTC, babisRoutis commented on src/main/kotlin/eu/europa/ec/eudi/pidissuer/security/DPoPTokenReactiveAuthenticationManager.kt
> +        Mono.just(authentication)
Can we remove the Mono implementation of the method?
Instead perhaps we can use the `mono()` method that accepts a suspended lamda

2024-04-22 10:54 UTC, babisRoutis commented on src/main/kotlin/eu/europa/ec/eudi/pidissuer/security/DPoPTokenReactiveAuthenticationManager.kt
> +        Mono.fromCallable {
Can we remove the Mono from implementation?
Use `mono()` which lifts a suspended lamda into Mono context instead.

2024-04-22 10:54 UTC, babisRoutis commented on src/main/kotlin/eu/europa/ec/eudi/pidissuer/security/DPoPTokenReactiveAuthenticationManager.kt
> +    Mono.justOrEmpty(attributes[OAuth2TokenIntrospectionClaimNames.CLIENT_ID])
Can we use `mono()` with a suspended lamda?

2024-04-22 10:54 UTC, babisRoutis commented on src/main/kotlin/eu/europa/ec/eudi/pidissuer/security/DPoPTokenReactiveAuthenticationManager.kt
> +    Mono.fromCallable { JSONObjectUtils.parse(JSONObject.toJSONString(attributes.filterKeys { it == "cnf" })) }
Can we use `mono()` with a suspended lamda?

2024-04-22 12:15 UTC, babisRoutis commented
@dzarras Removed comments related to implementation of methods using `Mono` data structure. We can deal with it after merge.

Please let me know as soon as you have prepared the conditional registration of DPoP authentication scheme

2024-04-22 12:57 UTC, babisRoutis submitted a review, later dismissed

2024-04-22 12:57 UTC, babisRoutis commented on src/main/kotlin/eu/europa/ec/eudi/pidissuer/security/DPoPConfigurationProperties.kt
> +        require(!proofMaxAge.isZero) { "'proofMaxAge' cannot be zero" }
I have the impression that there could be negative durations. 
Can you please double check this

2024-04-22 13:29 UTC, babisRoutis approved these changes

2024-04-22 13:30 UTC, merged